"""Generate reproducible Python scripts from Signal Analyzer sessions."""

from __future__ import annotations

from dataclasses import dataclass

from .signal_model import SignalRecord


@dataclass(slots=True)
class SessionExport:
    """Session payload used by script generator."""

    records: list[SignalRecord]


class ScriptGenerator:
    """Creates standalone scipy/numpy scripts from in-memory session state."""

    def generate_script(self, session: SessionExport) -> str:
        """Return a complete Python script that recreates current session."""
        lines: list[str] = [
            "#!/usr/bin/env python3",
            '"""Generated by Kronos Signal Analyzer."""',
            "",
            "import numpy as np",
            "from scipy import signal",
            "import matplotlib.pyplot as plt",
            "",
            "",
            "def main() -> None:",
            "    signals = {}",
        ]

        for idx, record in enumerate(session.records):
            name = f"signal_{idx + 1}"
            data_literal = ", ".join(f"{float(v):.12g}" for v in record.data[:5000])
            if record.data.size > 5000:
                data_literal += ",  # truncated by generator"
            lines.extend(
                [
                    f"    # Source: {record.source}; Name: {record.name}",
                    f"    {name} = np.array([{data_literal}], dtype=float)",
                    f"    fs_{idx + 1} = {float(record.fs):.12g}",
                    f"    t_{idx + 1} = {float(record.start_time):.12g} + np.arange({name}.size) / fs_{idx + 1}",
                    f"    signals[{record.name!r}] = ({name}, fs_{idx + 1}, t_{idx + 1})",
                    "",
                ]
            )
            if record.preprocessing_log:
                lines.append("    # Preprocessing history:")
                for entry in record.preprocessing_log:
                    lines.append(f"    #   - {entry}")
                lines.append("")

        lines.extend(
            [
                "    fig, axes = plt.subplots(2, 1, figsize=(10, 7), constrained_layout=True)",
                "    for name, (data, fs, t) in signals.items():",
                "        axes[0].plot(t, data, label=name)",
                "        freq, psd = signal.welch(data, fs=fs, nperseg=min(1024, data.size))",
                "        axes[1].semilogy(freq, np.maximum(psd, 1e-18), label=name)",
                "",
                "    axes[0].set_title('Time Domain')",
                "    axes[0].set_xlabel('Time (s)')",
                "    axes[0].set_ylabel('Amplitude')",
                "    axes[0].grid(True, alpha=0.3)",
                "    axes[0].legend()",
                "",
                "    axes[1].set_title('Power Spectral Density (Welch)')",
                "    axes[1].set_xlabel('Frequency (Hz)')",
                "    axes[1].set_ylabel('PSD')",
                "    axes[1].grid(True, alpha=0.3)",
                "    axes[1].legend()",
                "",
                "    for name, (data, fs, _t) in signals.items():",
                "        rms = float(np.sqrt(np.mean(np.square(data))))",
                "        print(f'{name}: RMS={rms:.6g}, min={float(np.min(data)):.6g}, max={float(np.max(data)):.6g}')",
                "",
                "    plt.show()",
                "",
                "",
                "if __name__ == '__main__':",
                "    main()",
                "",
            ]
        )

        return "\n".join(lines)
